### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by rodrigopasc** [isitgeorge/serverless-offline-multi#3]
Hi, how are you?

When I try to run with my services I get this output:

```
Unexpected error while starting serverless-offline lambda server on port 3002: { Error: listen EADDRINUSE: address already in use 127.0.0.1:3002
     at Server.setupListenHandle [as _listen2] (net.js:1270:14)
     at listenInCluster (net.js:1318:12)
     at GetAddrInfoReqWrap.doListen (net.js:1451:7)
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
   code: 'EADDRINUSE',
   errno: 'EADDRINUSE',
   syscall: 'listen',
   address: '127.0.0.1',
   port: 3002 }
```

How can I solve this?

Thank you.

**Comment by rodrigopasc** [comment]
I found the problem. It is not compatible with `serverless-offline` version (6.0.0+).

Do you have plans for adding support to it?

Thank you for your time.

**Comment by rodrigopasc** [comment]
I solved the problem - not the best possible way, I think, but it worked.

https://github.com/isitgeorge/serverless-offline-multi/pull/4
